name: Build Android APK
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    # Добавляем переменную, чтобы использовать актуальный Node.js
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4 # Проверьте наличие v5, если ошибка останется
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI Workload
        # Устанавливаем только Android, чтобы было быстрее и надежнее
        run: dotnet workload install maui-android
      - name: Restore dependencies
        run: dotnet restore maui-client/BridgeToFreedom.sln
      - name: Build APK
        run: |
          cd maui-client
          dotnet publish -f net8.0-android -c Release /p:AndroidKeyStore=false
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-to-freedom-apk
          path: maui-client/bin/Release/net8.0-android/publish/*.apk

