name: Build Android APK
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Android Workload
        run: dotnet workload install maui-android

      - name: Build APK
        run: |
          # Мы заходим в папку и ищем файл проекта .csproj (он там точно есть)
          cd maui-client
          dotnet publish -f net8.0-android -c Release /p:AndroidKeyStore=false
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-to-freedom-apk
          # Используем маску **, чтобы GitHub сам нашел APK в папках bin или publish
          path: maui-client/**/publish/*.apk


