name: Build Android APK
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    env:
      # Решаем проблему с версией Node.js
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI Android Workload
        run: dotnet workload install maui-android

      - name: Restore dependencies
        # Используем поиск всех .sln файлов в папке maui-client
        run: dotnet restore maui-client/*.sln

      - name: Build APK
        run: |
          cd maui-client
          # Собираем проект. Параметр /p:AndroidKeyStore=false позволяет собрать без цифровой подписи
          dotnet publish -f net8.0-android -c Release /p:AndroidKeyStore=false /p:ErrorOnDuplicatePublishOutputFiles=false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bridge-to-freedom-apk
          # Этот путь стандартный для MAUI, GitHub найдет там готовый APK
          path: maui-client/bin/Release/net8.0-android/publish/*.apk

